# Generated by Django 2.2.9 on 2020-01-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('phone', models.CharField(default='', max_length=13)),
                ('email', models.CharField(default='', max_length=255)),
                ('content', models.TextField()),
            ],
        ),
    ]
